apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
spec:
  clusterIP: None
  ports:
    - name: broker
      port: 9092
    - name: external
      port: 9093
  selector:
    app: kafka
