apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-0-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/docker/data/kafka-data/kafka-0
    type: DirectoryOrCreate
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-0-pvc
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: kafka-0-pv
