# Define PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/docker/data/zookeeper-data/zk1
    type: DirectoryOrCreate
  storageClassName: "standard" # change to your storage class

---
# Define PersistentVolumeClaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk1-pvc
  namespace: zk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "standard"
  volumeName: zk1-pv
